disable_response_storage = true
model = "gpt-5.1-codex"
model_reasoning_effort = "high"
model_provider = "crs"

[model_providers.crs]
base_url = "https://ai.imgwwo.top/v1"
name = "crs"
requires_openai_auth = true
wire_api = "responses"

[mcp_servers.CodexTools]
command = "D:/python/CodexTools/.venv/Scripts/python.exe"
args = ["-u", "-X", "utf8", "D:/python/CodexTools/server.py"]
enabled = true

[mcp_servers.spec-workflow]
command = "npx"
args = ["-y", "@pimzino/spec-workflow-mcp@latest", "D:/java/github"]
enabled = true

[mcp_servers.memorix]
command = "memorix"
args = ["serve"]
enabled = true
